"use client";
import { useState } from "react";
import * as m from "@/lib/mock";
import Icon from "./icons";

export const money = value => (value < 0 ? "−" : "") + "$" + Math.abs(value).toLocaleString("en-US", { maximumFractionDigits: 0 });
export const integrations = [
  { name: "Neon", mark: "N", color: "mint", description: "Your memory, connected.", detail: "Postgres storage and AI Gateway for model access.", icon: "code" },
  { name: "Mastra", mark: "M", color: "peach", description: "The brains behind the team.", detail: "Agent framework, observability, and agent factory.", icon: "spark" },
  { name: "Exa", mark: "exa", color: "blue", description: "Find the signal in the noise.", detail: "Web search and crawling for evidence-backed research.", icon: "search" },
  { name: "Fly.io", mark: "F", color: "lilac", description: "A space for agents to work.", detail: "Sprites sandboxes for isolated agent execution.", icon: "code" },
  { name: "Kernel", mark: "K", color: "peach", description: "A helping hand on the web.", detail: "Browser automation for multi-step online tasks.", icon: "globe" },
  { name: "Executor", mark: "E", color: "mint", description: "Your tools, working together.", detail: "Tools and MCP gateway for agent connections.", icon: "bolt" },
  { name: "Assistant UI", mark: "a", color: "lilac", description: "A conversation that flows.", detail: "Planned agent chat components and streaming interface.", icon: "chat" },
  { name: "AgentMail", mark: "@", color: "blue", description: "An inbox for every agent.", detail: "Agent email inboxes for receiving and preparing messages.", icon: "mail" },
  { name: "Anam.ai", mark: "a.", color: "pink", description: "A face to your sidekick.", detail: "Real-time conversational avatar and voice experience.", icon: "heart" },
];
const agentStyles = [{ icon: "wallet", color: "mint", short: "Money mate" }, { icon: "calendar", color: "lilac", short: "Life planner" }, { icon: "heart", color: "peach", short: "Wellbeing buddy" }, { icon: "globe", color: "blue", short: "Deep diver" }];

export function CardHeading({ title, eyebrow, action, onAction }) {
  return <div className="card-heading"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{action && <button className="text-button" onClick={onAction}>{action}<Icon name="arrow" size={15}/></button>}</div>;
}
export function Spark({ data, className = "", fill = false, domain }) {
  const min = domain ? domain[0] : Math.min(...data) * .98, max = domain ? domain[1] : Math.max(...data) * 1.01;
  const pts = data.map((v, i) => `${i / (data.length - 1) * 300},${100 - (v - min) / (max - min || 1) * 100}`).join(" ");
  return <svg className={"sparkline " + className} viewBox="0 0 300 100" preserveAspectRatio="none" role="img" aria-label={`Trend from ${data[0]} to ${data[data.length - 1]}`}>{fill && <polygon points={`0,100 ${pts} 300,100`} fill="currentColor" opacity=".09"/>}<polyline points={pts} fill="none" stroke="currentColor" strokeWidth="2.6" vectorEffect="non-scaling-stroke" strokeLinejoin="round" strokeLinecap="round"/></svg>;
}
function Metrics() {
  return <div className="metrics-grid">
    <article className="metric-card"><div className="metric-top"><span className="icon-tile mint"><Icon name="wallet" size={18}/></span><span>Net worth</span><Icon name="up" size={16}/></div><strong>{money(m.accounts.reduce((sum, item) => sum + item.balance, 0))}</strong><div className="metric-bottom"><span className="positive"><Icon name="up" size={13}/> 1.9%</span><span>this month</span></div><Spark data={m.netWorthHistory}/></article>
    <article className="metric-card"><div className="metric-top"><span className="icon-tile lilac"><Icon name="bolt" size={18}/></span><span>Monthly cash flow</span><Icon name="up" size={16}/></div><strong>+{money(m.cashFlow.income - m.cashFlow.spend)}</strong><div className="metric-bottom"><span className="positive">Looking good</span><span>September</span></div><div className="cash-bars" aria-hidden="true">{[32, 52, 38, 65, 48, 78, 63, 84, 69, 94, 82, 100].map((v, i) => <i key={i} style={{ height: v + "%" }}/>)}</div></article>
    <article className="metric-card"><div className="metric-top"><span className="icon-tile peach"><Icon name="heart" size={18}/></span><span>Your vitality</span><Icon name="up" size={16}/></div><strong>{m.health.vitality}<small>/100</small></strong><div className="metric-bottom"><span className="positive">A good place to be</span></div><div className="mini-ring" style={{ "--score": m.health.vitality + "%" }}><Icon name="heart" size={19}/></div></article>
  </div>;
}
export function Approvals({ items, decide, compact = false, history = [], reset }) {
  return <section className={"card approvals-card" + (compact ? " compact-approvals" : "")}>{!compact && <><CardHeading title="A little input from you" eyebrow="YOU’RE IN CONTROL"/><p className="card-description">Your agents did the legwork. You make the call.</p></>}
    {items.length === 0 ? <div className="empty-state"><span className="icon-tile mint"><Icon name="check" size={24}/></span><h3>All clear. Go do your thing.</h3><p>No decisions waiting on you.</p></div> : <div className="approval-list">{items.slice(0, compact ? 2 : undefined).map((item) => <div className="approval-item" key={item.id}><span className={"icon-tile " + (item.kind === "Calendar" ? "lilac" : "peach")}><Icon name={item.kind === "Calendar" ? "calendar" : item.kind === "Dispute" ? "mail" : "wallet"} size={19}/></span><div className="approval-copy"><span className="overline">{item.kind} <span>· {item.agent}</span></span><h3>{item.title}</h3><p>{item.reason}</p><div className="approval-actions"><button className="button button-small" onClick={() => decide(item, true)}><Icon name="check" size={14}/> Approve</button><button className="text-button subdued" onClick={() => decide(item, false)}>Decline</button></div></div></div>)}</div>}
    {!compact && history.length > 0 && <div className="decision-history"><h3>Decision history</h3>{history.map(item => <div className="data-row" key={item.id}><span>{item.title}</span><span className={"status " + (item.approved ? "mint" : "peach")}>{item.approved ? "Approved" : "Declined"}</span></div>)}</div>}
    {!compact && <div className="demo-notice"><Icon name="shield" size={16}/><span>Demo decisions are saved in this browser. No payments, emails, or calendar changes are made.</span>{reset && <button className="text-button" onClick={reset}>Reset demo</button>}</div>}
  </section>;
}
export function Overview({ approvals, decide, navigate, ask }) {
  const [period, setPeriod] = useState("1Y");
  const values = period === "6M" ? m.netWorthHistory.slice(-6) : m.netWorthHistory;
  const growth = ((values[values.length - 1] / values[0] - 1) * 100).toFixed(1);
  return <div className="overview-view">
    <div className="overview-top"><section className="daily-hero"><div className="hero-copy"><span className="hero-pill"><span/> YOUR DAILY EXHALE</span><h2>Less life admin.<br/>More <span>living.</span></h2><p>Your whole world. A little more breathing room.</p><button className="button dark-button" onClick={() => ask("Give me my daily brief")}><Icon name="spark" size={16}/> Give me the rundown<Icon name="arrow" size={16}/></button></div><div className="hero-art" aria-hidden="true"><div className="hero-orbit"/><div className="hero-omni"><img src="/omni.png" alt=""/><span className="hero-omni-tag">Omni</span></div><span className="floating-label label-top"><span className="small-check">✓</span> More headspace</span><span className="floating-label label-bottom"><Icon name="spark" size={16}/> You’ve got this.</span><span className="hero-star">✦</span></div><span className="hero-footnote">A calmer kind of productive.</span></section>
    <Metrics/></div>
    <div className="overview-columns"><section className="card wealth-card"><CardHeading title="Making money moves" action="Your money" onAction={() => navigate("finance")}/><div className="wealth-summary"><div><span className="muted small">Net worth trend</span><strong>$901.9<span>k</span><small className="positive">↗ {growth}%</small></strong></div><div className="segmented" aria-label="Chart period">{["6M", "1Y"].map(p => <button key={p} className={period === p ? "selected" : ""} aria-pressed={period === p} onClick={() => setPeriod(p)}>{p}</button>)}</div></div><div className="wealth-chart"><div className="chart-grid"><span>$950k</span><span>$850k</span><span>$750k</span></div><Spark data={values} fill domain={[750, 950]}/><div className="chart-labels">{(period === "6M" ? ["MAY", "JUN", "JUL", "AUG", "SEP", "OCT"] : ["NOV", "JAN", "MAR", "MAY", "JUL", "OCT"]).map(label => <span key={label}>{label}</span>)}</div></div><div className="chart-caption"><span className="legend-dot"/> Your long game is looking good.<span>Sample data</span></div></section>
    <section className="card agenda-card"><CardHeading title="On the horizon" action="Calendar" onAction={() => navigate("family")}/><div className="week-strip">{["M", "T", "W", "T", "F", "S", "S"].map((day, i) => <div className={i === 0 ? "active-day" : ""} key={i}><span>{day}</span><b>{5 + i}</b>{[0, 1, 2, 3, 5].includes(i) && <i/>}</div>)}</div><span className="overline agenda-date">MONDAY, OCTOBER 5</span>{m.events.slice(0, 2).map((event, i) => <div className="agenda-event" key={event.title}><span className="agenda-time">{event.time}</span><span className={"event-line " + (i ? "peach-line" : "purple-line")}/><div><h3>{event.title}</h3><p>{event.who} <span>· {event.tag}</span></p></div></div>)}<button className="conflict-note" onClick={() => navigate("approvals")}><Icon name="bolt" size={16}/><span>One overlap on Tuesday. Let’s fix it.</span><Icon name="arrow" size={15}/></button></section></div>
    <div className="overview-bottom"><section className="decisions-section"><div className="section-heading"><h2>Your next moves <span className="count-badge">{approvals.length}</span></h2><button className="text-button" onClick={() => navigate("approvals")}>Review all<Icon name="arrow" size={15}/></button></div>
    <Approvals items={approvals} decide={decide} compact/></section>
    <section className="squad-section"><div className="section-heading"><h2>Your support system</h2><button className="text-button" onClick={() => navigate("agents")}>View all<Icon name="arrow" size={15}/></button></div><div className="squad-grid">{m.agents.map((agent, i) => <button className="squad-card" key={agent.name} onClick={() => navigate("agents")}><span className={"icon-tile " + agentStyles[i].color}><Icon name={agentStyles[i].icon}/></span><h3>{agentStyles[i].short}</h3><p>{agent.task}</p><span className="agent-status"><i className={agent.status === "idle" ? "idle" : ""}/>{agent.status === "idle" ? "Taking a breather" : "On it"}<span>Demo</span></span></button>)}</div></section>
    </div>
  </div>;
}
export function Finance() {
  return <><Metrics/><div className="two-columns"><section className="card"><CardHeading title="Your money, in one place" eyebrow="ACCOUNTS"/>{m.accounts.map(account => <div className="data-row" key={account.id}><span className={"icon-tile " + (account.balance < 0 ? "peach" : "mint")}><Icon name="wallet" size={17}/></span><div className="row-copy"><h3>{account.name}</h3><p>{account.type}</p></div><b className={account.balance < 0 ? "negative" : ""}>{money(account.balance)}</b></div>)}</section><section className="card"><CardHeading title="Room in the budget" eyebrow="THIS MONTH"/>{m.budget.map(item => <div className="budget-row" key={item.cat}><div><h3>{item.cat}</h3><span><b className={item.spent > item.limit ? "negative" : ""}>{money(item.spent)}</b> / {money(item.limit)}</span></div><div className="progress-track"><i className={item.spent > item.limit ? "over-budget" : ""} style={{ width: Math.min(100, item.spent / item.limit * 100) + "%" }}/></div></div>)}<div className="insight-note"><Icon name="spark" size={19}/><p>Utilities and dining are a little over. A small reset could make next month feel lighter.</p></div></section></div><section className="card"><CardHeading title="Bills without the mental load" eyebrow="UPCOMING & RECENT"/>{m.bills.map(bill => <div className="data-row" key={bill.id}><span className="icon-tile lilac"><Icon name="inbox" size={18}/></span><div className="row-copy"><h3>{bill.payee}</h3><p>Due {bill.due} · {bill.note}</p></div><b>{money(bill.amount)}</b><span className={"status " + (["anomaly", "approval"].includes(bill.status) ? "peach" : "mint")}>{bill.status}</span></div>)}</section></>;
}
export function Family({ navigate }) {
  return <><section className="family-banner"><div><span className="eyebrow">YOUR PEOPLE, YOUR PLANS</span><h2>Life’s better, together.</h2><p>A little less coordinating. A lot more showing up.</p></div><div className="family-avatars">{m.family.map(member => <span key={member.name} title={member.name} style={{ background: member.color }}>{member.name[0]}</span>)}</div></section><div className="two-columns"><section className="card"><CardHeading title="The week ahead" eyebrow="OCTOBER 5–11"/>{m.events.map(event => <div className="data-row" key={event.title}><span className="event-date"><b>{event.day.split(" ")[0]}</b><span>{event.time}</span></span><div className="row-copy"><h3>{event.title}</h3><p>{event.who} · {event.tag}</p></div>{event.conflict && <button className="status peach" onClick={() => navigate("approvals")}>Overlap</button>}</div>)}</section><section className="card"><CardHeading title="The little things" eyebrow="FAMILY TO-DOS"/>{m.familyTasks.map(task => <div className="task-item" key={task.id}><span className="icon-tile lilac"><Icon name="calendar" size={18}/></span><div><h3>{task.title}</h3><p>{task.who} · Due {task.due}</p><span className="status lilac">{task.status}</span></div></div>)}<div className="travel-card"><Icon name="plane" size={27}/><span className="eyebrow">SOMETHING TO LOOK FORWARD TO</span><h3>Seattle, here we come.</h3><p>October 10–12 · Family weekend</p><span>{m.travel[0].detail}</span></div></section></div></>;
}
export function Health() {
  return <><section className="wellbeing-banner"><div><span className="eyebrow">CHECK IN WITH YOURSELF</span><h2>Small steps. Good energy.</h2><p>A snapshot of how you’re doing. No perfect scores needed.</p><span className="status mint">Today’s vitality · {m.health.vitality}/100</span></div><div className="vitality-ring" style={{ "--score": m.health.vitality + "%" }}><strong>{m.health.vitality}<span>FEELING GOOD</span></strong></div></section><div className="health-grid">{m.health.metrics.map((metric, i) => <section className="card health-metric" key={metric.k}><span className={"icon-tile " + ["lilac", "peach", "pink", "mint", "blue", "lilac"][i]}><Icon name={i === 0 ? "moon" : i === 4 ? "bolt" : "heart"}/></span><span className="muted">{metric.k}</span><strong>{metric.v}</strong><Spark data={metric.trend}/><span className="small muted">Last 7 days · Sample data</span></section>)}</div><section className="card"><CardHeading title="Gentle nudges" eyebrow="FROM YOUR WELLBEING BUDDY"/>{m.health.recs.map(rec => <div className="data-row" key={rec}><span className="icon-tile mint"><Icon name="spark" size={18}/></span><p>{rec}</p></div>)}<p className="small muted">Illustrative wellness insights from mock data, not a medical assessment.</p></section></>;
}
export function Agents({ history }) {
  return <><div className="agents-intro"><span className="hero-pill"><span/> YOUR PERSONAL DREAM TEAM</span><h2>Big help. Zero group chats.</h2><p>Specialists for the things that take up space in your head.</p></div><div className="agent-detail-grid">{m.agents.map((agent, i) => <section className="card agent-detail" key={agent.name}><div className="agent-detail-top"><span className={"icon-tile large-tile " + agentStyles[i].color}><Icon name={agentStyles[i].icon} size={26}/></span><span className="status neutral">Demo · {agent.status}</span></div><h2>{agentStyles[i].short}</h2><span className="muted small">{agent.name}</span><p>{agent.task}</p><div className="agent-detail-meta"><span><Icon name="mail" size={14}/>{agent.inbox}</span><span><Icon name="code" size={14}/>Mastra · {agent.runtime}</span></div></section>)}</div><div className="two-columns"><section className="card"><CardHeading title="Behind the scenes" eyebrow="BROWSER WORKSPACES · DEMO"/>{m.sandboxes.map(sandbox => <div className="sandbox-row" key={sandbox.id}><div><Icon name="globe" size={18}/><h3>{sandbox.site}</h3><span>{sandbox.progress}%</span></div><p>{sandbox.step}</p><div className="progress-track"><i style={{ width: sandbox.progress + "%" }}/></div><span className="small muted">Kernel browser · Sample session</span></div>)}</section><section className="card"><CardHeading title="Nothing behind your back" eyebrow="ACTIVITY LOG"/>{history.map(item => <div className="data-row audit-row" key={item.id}><Icon name="check" size={16}/><div><h3>{item.approved ? "Approved" : "Declined"} · {item.title}</h3><p>Your demo decision</p></div></div>)}{m.auditLog.map(log => <div className="data-row audit-row" key={log.t}><time>{log.t}</time><div><h3>{log.actor}</h3><p>{log.action}</p></div><span className="small muted">Demo</span></div>)}</section></div></>;
}
export function Connections() {
  return <><div className="connections-intro"><span className="eyebrow">GOOD THINGS WORK BETTER TOGETHER</span><h2>Your world. Connected.</h2><p>The stack behind your future personal operating system.</p><div className="demo-notice"><Icon name="code" size={17}/><span>This dashboard is a working UI demo. These nine services are planned integrations and are not connected yet.</span></div></div><div className="connections-grid">{integrations.map(integration => <section className="card connection-card" key={integration.name}><div className="connection-top"><span className={"provider-mark " + integration.color}>{integration.mark}</span><span className="status neutral">Not connected</span></div><h2>{integration.name}</h2><h3>{integration.description}</h3><p>{integration.detail}</p><span className="connection-footer"><Icon name={integration.icon} size={15}/> Planned integration</span></section>)}</div></>;
}
